---
name: release
on:
  push:
    tags:
      - "v*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: describe plugin
        id: plugin_description
        run: echo "::set-output name=api_version::$(go run . describe | jq -r '.api_version')"
      - name: release
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          API_VERSION: ${{ steps.plugin_description.outputs.api_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
